import { Router, type IRouter, type Request, type Response } from "express";
import { eq } from "drizzle-orm";
import { getProvider, SuggestInputSchema } from "@workspace/ai";
import { brandKitTable, db } from "@workspace/db";
import { checkAndIncrementAiCount } from "../services/billingService";
import { aiSuggestLimiter } from "../middlewares/rateLimit";
import { z } from "zod";

const router: IRouter = Router();

const AiSuggestBody = z.object({
  prompt: z.string().min(3).max(500),
});

/**
 * POST /api/ai/suggest
 *
 * Returns a Studio-ready { headline, bodyText, ctaText } triple generated by
 * the configured LLM provider (AI_PROVIDER env: 'anthropic' | 'openai').
 * Brand voice from the user's brand_kit row is merged into the system
 * prompt. Quota is enforced via billingService.
 */
router.post(
  "/ai/suggest",
  aiSuggestLimiter,
  async (req: Request, res: Response): Promise<void> => {
    if (!req.isAuthenticated()) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    const parsed = AiSuggestBody.safeParse(req.body);
    if (!parsed.success) {
      res.status(400).json({
        error: parsed.error.issues[0]?.message ?? "Invalid prompt",
      });
      return;
    }

    const [brand] = await db
      .select()
      .from(brandKitTable)
      .where(eq(brandKitTable.userId, req.user.id));

    const provider = getProvider();

    let result: Awaited<ReturnType<typeof provider.suggest>>;
    try {
      const input = SuggestInputSchema.parse({
        prompt: parsed.data.prompt,
        brand: {
          companyName: brand?.companyName ?? null,
          voice: brand?.brandVoice ?? null,
          voiceDescription: brand?.voiceDescription ?? null,
        },
      });

      result = await provider.suggest(input);
    } catch (err) {
      req.log.error(
        { err, provider: provider.name },
        "AI suggest provider call failed",
      );
      res
        .status(502)
        .json({ error: "AI provider could not generate a suggestion" });
      return;
    }

    // Charge quota only AFTER a successful generation — a provider 502 must not
    // burn a Free user's monthly unit for a result they never got (mirrors the
    // render path not consuming quota on failure). Abuse is already bounded by
    // aiSuggestLimiter, so deferring the increment past the LLM call is safe.
    try {
      await checkAndIncrementAiCount(req.user.id);
    } catch (err) {
      const e = err as { reason?: string; message?: string };
      if (e.reason === "upgrade_required") {
        res.status(403).json({
          error: e.message ?? "AI suggestion limit reached",
          reason: "upgrade_required",
        });
        return;
      }
      throw err;
    }

    res.status(200).json({
      headline: result.headline,
      bodyText: result.bodyText,
      ctaText: result.ctaText,
    });
  },
);

export default router;
